#以下是测试和正式环境通用配置
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /mq


spring:
  mvc:
    view:
      prefix: /resources/static/
      suffix: .html

#对于rabbitMQ的支持
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


#    listener:
#      direct:
#        acknowledge-mode:
#      simple:
#        acknowledge-mode: